[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.0 --activate",
  "pnpm install --frozen-lockfile=false --prod=false"
]

[phases.build]
cmds = ["pnpm run build:prod"]

[start]
cmd = "pnpm run start:prod"
