[build]
builder = "NIXPACKS"
# Deploy trigger: 2026-07-16
buildCommand = "pnpm run build:prod"

[deploy]
startCommand = "pnpm run start:prod"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
